version: 2
updates:
  # Enable version updates for Go
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "fabricio"
    assignees:
      - "fabricio"
    labels:
      - "dependencies"
      - "automated"
      - "chore"
    commit-message:
      prefix: "chore"
      include: "scope"
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "github.com/Azure/azure-sdk-for-go/sdk/messaging/azservicebus"
        update-types: ["version-update:semver-major"]
      - dependency-name: "github.com/spf13/cobra"
        update-types: ["version-update:semver-major"]
      - dependency-name: "github.com/fatih/color"
        update-types: ["version-update:semver-major"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "fabricio"
    assignees:
      - "fabricio"
    labels:
      - "dependencies"
      - "automated"
      - "chore"
    commit-message:
      prefix: "ci"
      include: "scope"